
export const CLOSE_ASIDE_ACCESS_GROUPE = "CLOSE_ASIDE_ACCESS_GROUPE";
export const RESET_ASIDE_ACCESS_GROUPE = "RESET_ASIDE_ACCESS_GROUPE";
export const SHOW_ASIDE_ACCESS_MODE_GROUPE = "SHOW_ASIDE_ACCESS_MODE_GROUPE";
export const SHOW_MODAL_CONFIRMATION_GROUPE = "SHOW_MODAL_CONFIRMATION_GROUPE";
export const CLOSE_MODAL_CONFIRMATION_GROUPE = "CLOSE_MODAL_CONFIRMATION_GROUPE";
export const GET_ACCESS_MODULE_GRP = "GET_ACCESS_MODULE_GRP";

