export const CLOSE_ASIDE_ACCESS_USER = "CLOSE_ASIDE_ACCESS_USER";
export const RESET_ASIDE_ACCESS_USER = "RESET_ASIDE_ACCESS_USER";
export const SHOW_ASIDE_ACCESS_MODE_USER = "SHOW_ASIDE_ACCESS_MODE_USER";
export const SHOW_MODAL_CONFIRMATION_USER = "SHOW_MODAL_CONFIRMATION_USER";
export const CLOSE_MODAL_CONFIRMATION_USER = "CLOSE_MODAL_CONFIRMATION_USER";

