//import { GET_ALL_GROUPE } from "../Groupe/GroupeAside";

export const SHOW_ASIDE_ADD_MODE_UTILISATEUR = "SHOW_ASIDE_ADD_MODE_UTILISATEUR";
export const CLOSE_ASIDE_UTILISATEUR = "CLOSE_ASIDE_UTILISATEUR";
export const RESET_ASIDE_UTILISATEUR = "RESET_ASIDE_UTILISATEUR";
export const GET_COMPTEUR_UTILISATEUR = "GET_COMPTEUR_UTILISATEUR";
export const SHOW_ASIDE_EDIT_MODE_UTILISATEUR = "SHOW_ASIDE_EDIT_MODE_UTILISATEUR";
export const SHOW_ASIDE_DELETE_MODE_UTILISATEUR = "SHOW_ASIDE_DELETE_MODE_UTILISATEUR";
export const SHOW_ASIDE_CONSULT_MODE_UTILISATEUR = "SHOW_ASIDE_CONSULT_MODE_UTILISATEUR";
export const SHOW_MODAL_CONFIRMATION_UTILISATEUR = "SHOW_MODAL_CONFIRMATION_UTILISATEUR";
export const CLOSE_MODAL_CONFIRMATION_UTILISATEUR = "CLOSE_MODAL_CONFIRMATION_UTILISATEUR";
export const GET_ALL_UTILISATEUR = "GET_ALL_UTILISATEUR";
export const GET_ALL_GROUPE = "GET_ALL_GROUPE";
export const GET_ALL_MODULES = "GET_ALL_MODULES";
export const GET_IMPRIME = "GET_IMPRIME";